# Flowable 工作流配置
flowable:
  # 将databaseSchemaUpdate设置为true。当Flowable发现库与数据库表结构不一致时，会自动将数据库表结构升级至新版本。
  # 1. false: 默认值，Flowable 启动时，对比数据库表中保存的版本，如果不匹配将抛出异常 ，可通过 https://github.com/flowable/flowable-sql 初始化
  # 2. true: 启动时会对数据库中所有表进行更新操作，如果表存在，不做处理，反之，自动创建表
  # 3. create-drop: 启动时自动创建表，关闭时自动删除表
  # 4. drop-create: 启动时，删除旧表，再创建新表
  database-schema-update: true
  async-executor-activate: false # 关闭定时任务JOB
  db-history-used: true # flowable6 默认 true 生成信息表，无需手动设置
  check-process-definitions: false # 设置为 false，禁用 /resources/processes 自动部署 BPMN XML 流程
  history-level: full # full：保存历史数据的最高级别，可保存全部流程相关细节，包括流程流转各节点参数
